[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "pbarticles"
authors = [{name = "Bob Belderbos", email = "bob@pybit.es"}]
dynamic = ["version", "description"]

[project.urls]
Home = "https://github.com/bbelderbos/pb_articles"
